// headapps/spa-starters/angular/src/app/components/container/container.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { JssModule } from '@sitecore-jss/sitecore-jss-angular';
import { SxaComponent } from '../sxa.component';

@Component({
  selector: 'app-container',
  templateUrl: './container.component.html',
  imports: [CommonModule, JssModule],
})
export class ContainerComponent extends SxaComponent implements OnInit {
  placeholderName: string;
  wrapped: boolean;

  override ngOnInit() {
    super.ngOnInit();

    this.placeholderName = `container-${this.rendering.params?.DynamicPlaceholderId}`;
    this.wrapped = this.rendering.params?.Styles?.split(' ').includes('container');
  }

  get backgroundStyle() {
    const backgroundImage = this.rendering.params?.BackgroundImage;
    const mediaUrlPattern = new RegExp(/mediaurl="([^"]*)"/, 'i');
    if (!backgroundImage || !backgroundImage.match(mediaUrlPattern)) {
      return {};
    }
    const mediaUrl = backgroundImage.match(mediaUrlPattern)[1];
    return {
      backgroundImage: `url('${mediaUrl}')`,
    };
  }
}

// headapps/nextjs-starter/src/components/Container.tsx
import { JSX } from 'react';
import {
  ComponentParams,
  ComponentRendering,
  Placeholder,
} from '@sitecore-jss/sitecore-jss-nextjs';

interface ComponentProps {
  rendering: ComponentRendering & { params: ComponentParams };
  params: ComponentParams;
}

const DefaultContainer = (props: ComponentProps): JSX.Element => {
  const containerStyles = props.params && props.params.Styles ? props.params.Styles : '';
  const styles = `${props.params.GridParameters} ${containerStyles}`.trimEnd();
  const phKey = `container-${props.params.DynamicPlaceholderId}`;
  const id = props.params.RenderingIdentifier;
  const mediaUrlPattern = new RegExp(/mediaurl=\"([^"]*)\"/, 'i');
  const backgroundImage = props.params.BackgroundImage as string;
  let backgroundStyle: { [key: string]: string } = {};

  if (backgroundImage && backgroundImage.match(mediaUrlPattern)) {
    const mediaUrl = backgroundImage.match(mediaUrlPattern)?.[1] || '';

    backgroundStyle = {
      backgroundImage: `url('${mediaUrl}')`,
    };
  }

  return (
    <div className={`component container-default ${styles}`} id={id ? id : undefined}>
      <div className="component-content" style={backgroundStyle}>
        <div className="row">
          <Placeholder name={phKey} rendering={props.rendering} />
        </div>
      </div>
    </div>
  );
};

export const Default = (props: ComponentProps): JSX.Element => {
  const splitStyles = props.params?.Styles?.split(' ');

  if (splitStyles && splitStyles.includes('container')) {
    return (
      <div className="container-wrapper">
        <DefaultContainer {...props} />
      </div>
    );
  }

  return <DefaultContainer {...props} />;
};
