// headapps/nextjs-starter/src/components/components/container/Container.tsx
import Placeholder from 'components/content-sdk/Placeholder';
import React, { JSX } from 'react';
import { ComponentProps } from 'lib/component-props';
import { componentMap } from '.sitecore/component-map';

interface ContainerProps extends ComponentProps {
  params: ComponentProps['params'] & {
    BackgroundImage?: string;
    DynamicPlaceholderId: string;
  };
}

const Container = ({ params, rendering, page }: ContainerProps): JSX.Element => {
  const {
    styles,
    RenderingIdentifier: id,
    BackgroundImage: backgroundImage,
    DynamicPlaceholderId,
  } = params;
  const phKey = `container-${DynamicPlaceholderId}`;

  // Extract the mediaurl from rendering parameters
  const mediaUrlPattern = new RegExp(/mediaurl=\"([^"]*)\"/, 'i');

  let backgroundStyle: { [key: string]: string } = {};

  if (backgroundImage && backgroundImage.match(mediaUrlPattern)) {
    const mediaUrl = backgroundImage.match(mediaUrlPattern)?.[1] || '';

    backgroundStyle = {
      backgroundImage: `url('${mediaUrl}')`,
    };
  }

  return (
    <div className={`component container-default ${styles}`} id={id}>
      <div className="component-content" style={backgroundStyle}>
        <div className="row">
          <Placeholder name={phKey} rendering={rendering} page={page} componentMap={componentMap} />
        </div>
      </div>
    </div>
  );
};

export const Default = (props: ContainerProps): JSX.Element => {
  const styles = props.params?.styles?.split(' ');

  return styles?.includes('container') ? (
    <div className="container-wrapper">
      <Container {...props} />
    </div>
  ) : (
    <Container {...props} />
  );
};

// headapps/spa-starters/angular/src/app/components/container/container.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { JssModule } from '@sitecore-jss/sitecore-jss-angular';
import { SxaComponent } from '../sxa.component';

@Component({
  selector: 'app-container',
  templateUrl: './container.component.html',
  imports: [CommonModule, JssModule],
})
export class ContainerComponent extends SxaComponent implements OnInit {
  placeholderName: string;
  wrapped: boolean;

  override ngOnInit() {
    super.ngOnInit();

    this.placeholderName = `container-${this.rendering.params?.DynamicPlaceholderId}`;
    this.wrapped = this.rendering.params?.Styles?.split(' ').includes('container');
  }

  get backgroundStyle() {
    const backgroundImage = this.rendering.params?.BackgroundImage;
    const mediaUrlPattern = new RegExp(/mediaurl="([^"]*)"/, 'i');
    if (!backgroundImage || !backgroundImage.match(mediaUrlPattern)) {
      return {};
    }
    const mediaUrl = backgroundImage.match(mediaUrlPattern)[1];
    return {
      backgroundImage: `url('${mediaUrl}')`,
    };
  }
}
